package cn.xtits.job.mapper.base;

import cn.xtits.job.entity.TaskDetail;
import cn.xtits.job.entity.TaskDetailExample;
import java.util.List;

import cn.xtits.job.mapper.TaskDetailExtMapper;
import org.apache.ibatis.annotations.Param;

public interface TaskDetailMapper extends TaskDetailExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    long countByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    int insert(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    int insertSelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    List<TaskDetail> selectByExample(TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    TaskDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskDetail record, @Param("example") TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskDetail record, @Param("example") TaskDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskDetail record);
}