package cn.xtits.job.mapper.base;

import cn.xtits.job.entity.TaskExecute;
import cn.xtits.job.entity.TaskExecuteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskExecuteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    long countByExample(TaskExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    int insert(TaskExecute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    int insertSelective(TaskExecute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    List<TaskExecute> selectByExample(TaskExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    TaskExecute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskExecute record, @Param("example") TaskExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskExecute record, @Param("example") TaskExecuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskExecute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskExecute record);
}