package cn.xtits.job.entity;

import java.io.Serializable;
import java.util.Date;

public class TaskDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.AppId
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.OrganizeId
     *
     * @mbg.generated
     */
    private Integer organizeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.OrganizeName
     *
     * @mbg.generated
     */
    private String organizeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.TaskId
     *
     * @mbg.generated
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.Cron
     *
     * @mbg.generated
     */
    private String cron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.LocationId
     *
     * @mbg.generated
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.LocationName
     *
     * @mbg.generated
     */
    private String locationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.InspectItemId
     *
     * @mbg.generated
     */
    private Integer inspectItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.InspectItemName
     *
     * @mbg.generated
     */
    private String inspectItemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.InspectItemRemark
     *
     * @mbg.generated
     */
    private String inspectItemRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.TaskStatus
     *
     * @mbg.generated
     */
    private Integer taskStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.AuditFlag
     *
     * @mbg.generated
     */
    private Boolean auditFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.AreaPersonId
     *
     * @mbg.generated
     */
    private Integer areaPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.ManagerId
     *
     * @mbg.generated
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.Manager
     *
     * @mbg.generated
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.StartDate
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.EndDate
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.MakeBillMan
     *
     * @mbg.generated
     */
    private String makeBillMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.CreateDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.ModifyDate
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.Modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ip_taskdetail.DeleteFlag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ip_taskdetail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.Id
     *
     * @return the value of ip_taskdetail.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.Id
     *
     * @param id the value for ip_taskdetail.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.AppId
     *
     * @return the value of ip_taskdetail.AppId
     *
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.AppId
     *
     * @param appId the value for ip_taskdetail.AppId
     *
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.OrganizeId
     *
     * @return the value of ip_taskdetail.OrganizeId
     *
     * @mbg.generated
     */
    public Integer getOrganizeId() {
        return organizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.OrganizeId
     *
     * @param organizeId the value for ip_taskdetail.OrganizeId
     *
     * @mbg.generated
     */
    public void setOrganizeId(Integer organizeId) {
        this.organizeId = organizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.OrganizeName
     *
     * @return the value of ip_taskdetail.OrganizeName
     *
     * @mbg.generated
     */
    public String getOrganizeName() {
        return organizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.OrganizeName
     *
     * @param organizeName the value for ip_taskdetail.OrganizeName
     *
     * @mbg.generated
     */
    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName == null ? null : organizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.TaskId
     *
     * @return the value of ip_taskdetail.TaskId
     *
     * @mbg.generated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.TaskId
     *
     * @param taskId the value for ip_taskdetail.TaskId
     *
     * @mbg.generated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.Cron
     *
     * @return the value of ip_taskdetail.Cron
     *
     * @mbg.generated
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.Cron
     *
     * @param cron the value for ip_taskdetail.Cron
     *
     * @mbg.generated
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.LocationId
     *
     * @return the value of ip_taskdetail.LocationId
     *
     * @mbg.generated
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.LocationId
     *
     * @param locationId the value for ip_taskdetail.LocationId
     *
     * @mbg.generated
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.LocationName
     *
     * @return the value of ip_taskdetail.LocationName
     *
     * @mbg.generated
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.LocationName
     *
     * @param locationName the value for ip_taskdetail.LocationName
     *
     * @mbg.generated
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName == null ? null : locationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.InspectItemId
     *
     * @return the value of ip_taskdetail.InspectItemId
     *
     * @mbg.generated
     */
    public Integer getInspectItemId() {
        return inspectItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.InspectItemId
     *
     * @param inspectItemId the value for ip_taskdetail.InspectItemId
     *
     * @mbg.generated
     */
    public void setInspectItemId(Integer inspectItemId) {
        this.inspectItemId = inspectItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.InspectItemName
     *
     * @return the value of ip_taskdetail.InspectItemName
     *
     * @mbg.generated
     */
    public String getInspectItemName() {
        return inspectItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.InspectItemName
     *
     * @param inspectItemName the value for ip_taskdetail.InspectItemName
     *
     * @mbg.generated
     */
    public void setInspectItemName(String inspectItemName) {
        this.inspectItemName = inspectItemName == null ? null : inspectItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.InspectItemRemark
     *
     * @return the value of ip_taskdetail.InspectItemRemark
     *
     * @mbg.generated
     */
    public String getInspectItemRemark() {
        return inspectItemRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.InspectItemRemark
     *
     * @param inspectItemRemark the value for ip_taskdetail.InspectItemRemark
     *
     * @mbg.generated
     */
    public void setInspectItemRemark(String inspectItemRemark) {
        this.inspectItemRemark = inspectItemRemark == null ? null : inspectItemRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.Status
     *
     * @return the value of ip_taskdetail.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.Status
     *
     * @param status the value for ip_taskdetail.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.TaskStatus
     *
     * @return the value of ip_taskdetail.TaskStatus
     *
     * @mbg.generated
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.TaskStatus
     *
     * @param taskStatus the value for ip_taskdetail.TaskStatus
     *
     * @mbg.generated
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.AuditFlag
     *
     * @return the value of ip_taskdetail.AuditFlag
     *
     * @mbg.generated
     */
    public Boolean getAuditFlag() {
        return auditFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.AuditFlag
     *
     * @param auditFlag the value for ip_taskdetail.AuditFlag
     *
     * @mbg.generated
     */
    public void setAuditFlag(Boolean auditFlag) {
        this.auditFlag = auditFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.AreaPersonId
     *
     * @return the value of ip_taskdetail.AreaPersonId
     *
     * @mbg.generated
     */
    public Integer getAreaPersonId() {
        return areaPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.AreaPersonId
     *
     * @param areaPersonId the value for ip_taskdetail.AreaPersonId
     *
     * @mbg.generated
     */
    public void setAreaPersonId(Integer areaPersonId) {
        this.areaPersonId = areaPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.ManagerId
     *
     * @return the value of ip_taskdetail.ManagerId
     *
     * @mbg.generated
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.ManagerId
     *
     * @param managerId the value for ip_taskdetail.ManagerId
     *
     * @mbg.generated
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.Manager
     *
     * @return the value of ip_taskdetail.Manager
     *
     * @mbg.generated
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.Manager
     *
     * @param manager the value for ip_taskdetail.Manager
     *
     * @mbg.generated
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.StartDate
     *
     * @return the value of ip_taskdetail.StartDate
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.StartDate
     *
     * @param startDate the value for ip_taskdetail.StartDate
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.EndDate
     *
     * @return the value of ip_taskdetail.EndDate
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.EndDate
     *
     * @param endDate the value for ip_taskdetail.EndDate
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.MakeBillMan
     *
     * @return the value of ip_taskdetail.MakeBillMan
     *
     * @mbg.generated
     */
    public String getMakeBillMan() {
        return makeBillMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.MakeBillMan
     *
     * @param makeBillMan the value for ip_taskdetail.MakeBillMan
     *
     * @mbg.generated
     */
    public void setMakeBillMan(String makeBillMan) {
        this.makeBillMan = makeBillMan == null ? null : makeBillMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.CreateDate
     *
     * @return the value of ip_taskdetail.CreateDate
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.CreateDate
     *
     * @param createDate the value for ip_taskdetail.CreateDate
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.ModifyDate
     *
     * @return the value of ip_taskdetail.ModifyDate
     *
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.ModifyDate
     *
     * @param modifyDate the value for ip_taskdetail.ModifyDate
     *
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.Modifier
     *
     * @return the value of ip_taskdetail.Modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.Modifier
     *
     * @param modifier the value for ip_taskdetail.Modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ip_taskdetail.DeleteFlag
     *
     * @return the value of ip_taskdetail.DeleteFlag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ip_taskdetail.DeleteFlag
     *
     * @param deleteFlag the value for ip_taskdetail.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}