package cn.xtits.job.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskExecuteExample extends BaseQuery {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public TaskExecuteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBillNoIsNull() {
            addCriterion("BillNo is null");
            return (Criteria) this;
        }

        public Criteria andBillNoIsNotNull() {
            addCriterion("BillNo is not null");
            return (Criteria) this;
        }

        public Criteria andBillNoEqualTo(String value) {
            addCriterion("BillNo =", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoNotEqualTo(String value) {
            addCriterion("BillNo <>", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoGreaterThan(String value) {
            addCriterion("BillNo >", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoGreaterThanOrEqualTo(String value) {
            addCriterion("BillNo >=", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoLessThan(String value) {
            addCriterion("BillNo <", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoLessThanOrEqualTo(String value) {
            addCriterion("BillNo <=", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoLike(String value) {
            addCriterion("BillNo like", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoNotLike(String value) {
            addCriterion("BillNo not like", value, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoIn(List<String> values) {
            addCriterion("BillNo in", values, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoNotIn(List<String> values) {
            addCriterion("BillNo not in", values, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoBetween(String value1, String value2) {
            addCriterion("BillNo between", value1, value2, "billNo");
            return (Criteria) this;
        }

        public Criteria andBillNoNotBetween(String value1, String value2) {
            addCriterion("BillNo not between", value1, value2, "billNo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`Status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`Status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`Status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`Status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`Status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`Status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`Status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`Status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`Status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`Status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`Status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`Status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLocationIdIsNull() {
            addCriterion("LocationId is null");
            return (Criteria) this;
        }

        public Criteria andLocationIdIsNotNull() {
            addCriterion("LocationId is not null");
            return (Criteria) this;
        }

        public Criteria andLocationIdEqualTo(Integer value) {
            addCriterion("LocationId =", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdNotEqualTo(Integer value) {
            addCriterion("LocationId <>", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdGreaterThan(Integer value) {
            addCriterion("LocationId >", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("LocationId >=", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdLessThan(Integer value) {
            addCriterion("LocationId <", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdLessThanOrEqualTo(Integer value) {
            addCriterion("LocationId <=", value, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdIn(List<Integer> values) {
            addCriterion("LocationId in", values, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdNotIn(List<Integer> values) {
            addCriterion("LocationId not in", values, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdBetween(Integer value1, Integer value2) {
            addCriterion("LocationId between", value1, value2, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("LocationId not between", value1, value2, "locationId");
            return (Criteria) this;
        }

        public Criteria andLocationNameIsNull() {
            addCriterion("LocationName is null");
            return (Criteria) this;
        }

        public Criteria andLocationNameIsNotNull() {
            addCriterion("LocationName is not null");
            return (Criteria) this;
        }

        public Criteria andLocationNameEqualTo(String value) {
            addCriterion("LocationName =", value, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameNotEqualTo(String value) {
            addCriterion("LocationName <>", value, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameGreaterThan(String value) {
            addCriterion("LocationName >", value, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameGreaterThanOrEqualTo(String value) {
            addCriterion("LocationName >=", value, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameLessThan(String value) {
            addCriterion("LocationName <", value, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameLessThanOrEqualTo(String value) {
            addCriterion("LocationName <=", value, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameLike(String value) {
            addCriterion("LocationName like", value, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameNotLike(String value) {
            addCriterion("LocationName not like", value, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameIn(List<String> values) {
            addCriterion("LocationName in", values, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameNotIn(List<String> values) {
            addCriterion("LocationName not in", values, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameBetween(String value1, String value2) {
            addCriterion("LocationName between", value1, value2, "locationName");
            return (Criteria) this;
        }

        public Criteria andLocationNameNotBetween(String value1, String value2) {
            addCriterion("LocationName not between", value1, value2, "locationName");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("TaskId is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("TaskId is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Integer value) {
            addCriterion("TaskId =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Integer value) {
            addCriterion("TaskId <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Integer value) {
            addCriterion("TaskId >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TaskId >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Integer value) {
            addCriterion("TaskId <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("TaskId <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Integer> values) {
            addCriterion("TaskId in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Integer> values) {
            addCriterion("TaskId not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("TaskId between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TaskId not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeIsNull() {
            addCriterion("TaskBillCode is null");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeIsNotNull() {
            addCriterion("TaskBillCode is not null");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeEqualTo(String value) {
            addCriterion("TaskBillCode =", value, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeNotEqualTo(String value) {
            addCriterion("TaskBillCode <>", value, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeGreaterThan(String value) {
            addCriterion("TaskBillCode >", value, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TaskBillCode >=", value, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeLessThan(String value) {
            addCriterion("TaskBillCode <", value, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeLessThanOrEqualTo(String value) {
            addCriterion("TaskBillCode <=", value, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeLike(String value) {
            addCriterion("TaskBillCode like", value, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeNotLike(String value) {
            addCriterion("TaskBillCode not like", value, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeIn(List<String> values) {
            addCriterion("TaskBillCode in", values, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeNotIn(List<String> values) {
            addCriterion("TaskBillCode not in", values, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeBetween(String value1, String value2) {
            addCriterion("TaskBillCode between", value1, value2, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeNotBetween(String value1, String value2) {
            addCriterion("TaskBillCode not between", value1, value2, "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdIsNull() {
            addCriterion("TaskDetailId is null");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdIsNotNull() {
            addCriterion("TaskDetailId is not null");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdEqualTo(Integer value) {
            addCriterion("TaskDetailId =", value, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdNotEqualTo(Integer value) {
            addCriterion("TaskDetailId <>", value, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdGreaterThan(Integer value) {
            addCriterion("TaskDetailId >", value, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("TaskDetailId >=", value, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdLessThan(Integer value) {
            addCriterion("TaskDetailId <", value, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("TaskDetailId <=", value, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdIn(List<Integer> values) {
            addCriterion("TaskDetailId in", values, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdNotIn(List<Integer> values) {
            addCriterion("TaskDetailId not in", values, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("TaskDetailId between", value1, value2, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("TaskDetailId not between", value1, value2, "taskDetailId");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNull() {
            addCriterion("TaskType is null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIsNotNull() {
            addCriterion("TaskType is not null");
            return (Criteria) this;
        }

        public Criteria andTaskTypeEqualTo(String value) {
            addCriterion("TaskType =", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotEqualTo(String value) {
            addCriterion("TaskType <>", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThan(String value) {
            addCriterion("TaskType >", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TaskType >=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThan(String value) {
            addCriterion("TaskType <", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLessThanOrEqualTo(String value) {
            addCriterion("TaskType <=", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLike(String value) {
            addCriterion("TaskType like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotLike(String value) {
            addCriterion("TaskType not like", value, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeIn(List<String> values) {
            addCriterion("TaskType in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotIn(List<String> values) {
            addCriterion("TaskType not in", values, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeBetween(String value1, String value2) {
            addCriterion("TaskType between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andTaskTypeNotBetween(String value1, String value2) {
            addCriterion("TaskType not between", value1, value2, "taskType");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("ParentId is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("ParentId is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("ParentId =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("ParentId <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("ParentId >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ParentId >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("ParentId <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("ParentId <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("ParentId in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("ParentId not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("ParentId between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ParentId not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andMakeBillManIsNull() {
            addCriterion("MakeBillMan is null");
            return (Criteria) this;
        }

        public Criteria andMakeBillManIsNotNull() {
            addCriterion("MakeBillMan is not null");
            return (Criteria) this;
        }

        public Criteria andMakeBillManEqualTo(String value) {
            addCriterion("MakeBillMan =", value, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManNotEqualTo(String value) {
            addCriterion("MakeBillMan <>", value, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManGreaterThan(String value) {
            addCriterion("MakeBillMan >", value, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManGreaterThanOrEqualTo(String value) {
            addCriterion("MakeBillMan >=", value, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManLessThan(String value) {
            addCriterion("MakeBillMan <", value, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManLessThanOrEqualTo(String value) {
            addCriterion("MakeBillMan <=", value, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManLike(String value) {
            addCriterion("MakeBillMan like", value, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManNotLike(String value) {
            addCriterion("MakeBillMan not like", value, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManIn(List<String> values) {
            addCriterion("MakeBillMan in", values, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManNotIn(List<String> values) {
            addCriterion("MakeBillMan not in", values, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManBetween(String value1, String value2) {
            addCriterion("MakeBillMan between", value1, value2, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andMakeBillManNotBetween(String value1, String value2) {
            addCriterion("MakeBillMan not between", value1, value2, "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CreateDate is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CreateDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CreateDate =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CreateDate <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CreateDate >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateDate >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CreateDate <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CreateDate <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CreateDate in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CreateDate not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CreateDate between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CreateDate not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("ModifyDate is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("ModifyDate is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("ModifyDate =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("ModifyDate <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("ModifyDate >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ModifyDate >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("ModifyDate <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("ModifyDate <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("ModifyDate in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("ModifyDate not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("ModifyDate between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("ModifyDate not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("Modifier is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("Modifier is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("Modifier =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("Modifier <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("Modifier >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("Modifier >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("Modifier <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("Modifier <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("Modifier like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("Modifier not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("Modifier in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("Modifier not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("Modifier between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("Modifier not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DeleteFlag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DeleteFlag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("DeleteFlag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("DeleteFlag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("DeleteFlag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DeleteFlag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("DeleteFlag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DeleteFlag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("DeleteFlag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("DeleteFlag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DeleteFlag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DeleteFlag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andInspectDateIsNull() {
            addCriterion("InspectDate is null");
            return (Criteria) this;
        }

        public Criteria andInspectDateIsNotNull() {
            addCriterion("InspectDate is not null");
            return (Criteria) this;
        }

        public Criteria andInspectDateEqualTo(Date value) {
            addCriterion("InspectDate =", value, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateNotEqualTo(Date value) {
            addCriterion("InspectDate <>", value, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateGreaterThan(Date value) {
            addCriterion("InspectDate >", value, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateGreaterThanOrEqualTo(Date value) {
            addCriterion("InspectDate >=", value, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateLessThan(Date value) {
            addCriterion("InspectDate <", value, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateLessThanOrEqualTo(Date value) {
            addCriterion("InspectDate <=", value, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateIn(List<Date> values) {
            addCriterion("InspectDate in", values, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateNotIn(List<Date> values) {
            addCriterion("InspectDate not in", values, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateBetween(Date value1, Date value2) {
            addCriterion("InspectDate between", value1, value2, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDateNotBetween(Date value1, Date value2) {
            addCriterion("InspectDate not between", value1, value2, "inspectDate");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionIsNull() {
            addCriterion("InspectDescription is null");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionIsNotNull() {
            addCriterion("InspectDescription is not null");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionEqualTo(String value) {
            addCriterion("InspectDescription =", value, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionNotEqualTo(String value) {
            addCriterion("InspectDescription <>", value, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionGreaterThan(String value) {
            addCriterion("InspectDescription >", value, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("InspectDescription >=", value, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionLessThan(String value) {
            addCriterion("InspectDescription <", value, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionLessThanOrEqualTo(String value) {
            addCriterion("InspectDescription <=", value, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionLike(String value) {
            addCriterion("InspectDescription like", value, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionNotLike(String value) {
            addCriterion("InspectDescription not like", value, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionIn(List<String> values) {
            addCriterion("InspectDescription in", values, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionNotIn(List<String> values) {
            addCriterion("InspectDescription not in", values, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionBetween(String value1, String value2) {
            addCriterion("InspectDescription between", value1, value2, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionNotBetween(String value1, String value2) {
            addCriterion("InspectDescription not between", value1, value2, "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagIsNull() {
            addCriterion("InspectPassFLag is null");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagIsNotNull() {
            addCriterion("InspectPassFLag is not null");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagEqualTo(String value) {
            addCriterion("InspectPassFLag =", value, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagNotEqualTo(String value) {
            addCriterion("InspectPassFLag <>", value, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagGreaterThan(String value) {
            addCriterion("InspectPassFLag >", value, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagGreaterThanOrEqualTo(String value) {
            addCriterion("InspectPassFLag >=", value, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagLessThan(String value) {
            addCriterion("InspectPassFLag <", value, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagLessThanOrEqualTo(String value) {
            addCriterion("InspectPassFLag <=", value, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagLike(String value) {
            addCriterion("InspectPassFLag like", value, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagNotLike(String value) {
            addCriterion("InspectPassFLag not like", value, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagIn(List<String> values) {
            addCriterion("InspectPassFLag in", values, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagNotIn(List<String> values) {
            addCriterion("InspectPassFLag not in", values, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagBetween(String value1, String value2) {
            addCriterion("InspectPassFLag between", value1, value2, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagNotBetween(String value1, String value2) {
            addCriterion("InspectPassFLag not between", value1, value2, "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectFileIsNull() {
            addCriterion("InspectFile is null");
            return (Criteria) this;
        }

        public Criteria andInspectFileIsNotNull() {
            addCriterion("InspectFile is not null");
            return (Criteria) this;
        }

        public Criteria andInspectFileEqualTo(String value) {
            addCriterion("InspectFile =", value, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileNotEqualTo(String value) {
            addCriterion("InspectFile <>", value, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileGreaterThan(String value) {
            addCriterion("InspectFile >", value, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileGreaterThanOrEqualTo(String value) {
            addCriterion("InspectFile >=", value, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileLessThan(String value) {
            addCriterion("InspectFile <", value, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileLessThanOrEqualTo(String value) {
            addCriterion("InspectFile <=", value, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileLike(String value) {
            addCriterion("InspectFile like", value, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileNotLike(String value) {
            addCriterion("InspectFile not like", value, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileIn(List<String> values) {
            addCriterion("InspectFile in", values, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileNotIn(List<String> values) {
            addCriterion("InspectFile not in", values, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileBetween(String value1, String value2) {
            addCriterion("InspectFile between", value1, value2, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectFileNotBetween(String value1, String value2) {
            addCriterion("InspectFile not between", value1, value2, "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectManIsNull() {
            addCriterion("InspectMan is null");
            return (Criteria) this;
        }

        public Criteria andInspectManIsNotNull() {
            addCriterion("InspectMan is not null");
            return (Criteria) this;
        }

        public Criteria andInspectManEqualTo(String value) {
            addCriterion("InspectMan =", value, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManNotEqualTo(String value) {
            addCriterion("InspectMan <>", value, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManGreaterThan(String value) {
            addCriterion("InspectMan >", value, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManGreaterThanOrEqualTo(String value) {
            addCriterion("InspectMan >=", value, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManLessThan(String value) {
            addCriterion("InspectMan <", value, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManLessThanOrEqualTo(String value) {
            addCriterion("InspectMan <=", value, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManLike(String value) {
            addCriterion("InspectMan like", value, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManNotLike(String value) {
            addCriterion("InspectMan not like", value, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManIn(List<String> values) {
            addCriterion("InspectMan in", values, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManNotIn(List<String> values) {
            addCriterion("InspectMan not in", values, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManBetween(String value1, String value2) {
            addCriterion("InspectMan between", value1, value2, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andInspectManNotBetween(String value1, String value2) {
            addCriterion("InspectMan not between", value1, value2, "inspectMan");
            return (Criteria) this;
        }

        public Criteria andManagerIdIsNull() {
            addCriterion("ManagerId is null");
            return (Criteria) this;
        }

        public Criteria andManagerIdIsNotNull() {
            addCriterion("ManagerId is not null");
            return (Criteria) this;
        }

        public Criteria andManagerIdEqualTo(Integer value) {
            addCriterion("ManagerId =", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotEqualTo(Integer value) {
            addCriterion("ManagerId <>", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdGreaterThan(Integer value) {
            addCriterion("ManagerId >", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ManagerId >=", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLessThan(Integer value) {
            addCriterion("ManagerId <", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdLessThanOrEqualTo(Integer value) {
            addCriterion("ManagerId <=", value, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdIn(List<Integer> values) {
            addCriterion("ManagerId in", values, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotIn(List<Integer> values) {
            addCriterion("ManagerId not in", values, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdBetween(Integer value1, Integer value2) {
            addCriterion("ManagerId between", value1, value2, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ManagerId not between", value1, value2, "managerId");
            return (Criteria) this;
        }

        public Criteria andManagerIsNull() {
            addCriterion("Manager is null");
            return (Criteria) this;
        }

        public Criteria andManagerIsNotNull() {
            addCriterion("Manager is not null");
            return (Criteria) this;
        }

        public Criteria andManagerEqualTo(String value) {
            addCriterion("Manager =", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerNotEqualTo(String value) {
            addCriterion("Manager <>", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerGreaterThan(String value) {
            addCriterion("Manager >", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerGreaterThanOrEqualTo(String value) {
            addCriterion("Manager >=", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerLessThan(String value) {
            addCriterion("Manager <", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerLessThanOrEqualTo(String value) {
            addCriterion("Manager <=", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerLike(String value) {
            addCriterion("Manager like", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerNotLike(String value) {
            addCriterion("Manager not like", value, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerIn(List<String> values) {
            addCriterion("Manager in", values, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerNotIn(List<String> values) {
            addCriterion("Manager not in", values, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerBetween(String value1, String value2) {
            addCriterion("Manager between", value1, value2, "manager");
            return (Criteria) this;
        }

        public Criteria andManagerNotBetween(String value1, String value2) {
            addCriterion("Manager not between", value1, value2, "manager");
            return (Criteria) this;
        }

        public Criteria andSolveDateIsNull() {
            addCriterion("SolveDate is null");
            return (Criteria) this;
        }

        public Criteria andSolveDateIsNotNull() {
            addCriterion("SolveDate is not null");
            return (Criteria) this;
        }

        public Criteria andSolveDateEqualTo(Date value) {
            addCriterion("SolveDate =", value, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateNotEqualTo(Date value) {
            addCriterion("SolveDate <>", value, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateGreaterThan(Date value) {
            addCriterion("SolveDate >", value, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SolveDate >=", value, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateLessThan(Date value) {
            addCriterion("SolveDate <", value, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateLessThanOrEqualTo(Date value) {
            addCriterion("SolveDate <=", value, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateIn(List<Date> values) {
            addCriterion("SolveDate in", values, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateNotIn(List<Date> values) {
            addCriterion("SolveDate not in", values, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateBetween(Date value1, Date value2) {
            addCriterion("SolveDate between", value1, value2, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDateNotBetween(Date value1, Date value2) {
            addCriterion("SolveDate not between", value1, value2, "solveDate");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionIsNull() {
            addCriterion("SolveDescription is null");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionIsNotNull() {
            addCriterion("SolveDescription is not null");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionEqualTo(String value) {
            addCriterion("SolveDescription =", value, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionNotEqualTo(String value) {
            addCriterion("SolveDescription <>", value, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionGreaterThan(String value) {
            addCriterion("SolveDescription >", value, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("SolveDescription >=", value, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionLessThan(String value) {
            addCriterion("SolveDescription <", value, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionLessThanOrEqualTo(String value) {
            addCriterion("SolveDescription <=", value, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionLike(String value) {
            addCriterion("SolveDescription like", value, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionNotLike(String value) {
            addCriterion("SolveDescription not like", value, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionIn(List<String> values) {
            addCriterion("SolveDescription in", values, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionNotIn(List<String> values) {
            addCriterion("SolveDescription not in", values, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionBetween(String value1, String value2) {
            addCriterion("SolveDescription between", value1, value2, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionNotBetween(String value1, String value2) {
            addCriterion("SolveDescription not between", value1, value2, "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveFileIsNull() {
            addCriterion("SolveFile is null");
            return (Criteria) this;
        }

        public Criteria andSolveFileIsNotNull() {
            addCriterion("SolveFile is not null");
            return (Criteria) this;
        }

        public Criteria andSolveFileEqualTo(String value) {
            addCriterion("SolveFile =", value, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileNotEqualTo(String value) {
            addCriterion("SolveFile <>", value, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileGreaterThan(String value) {
            addCriterion("SolveFile >", value, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileGreaterThanOrEqualTo(String value) {
            addCriterion("SolveFile >=", value, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileLessThan(String value) {
            addCriterion("SolveFile <", value, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileLessThanOrEqualTo(String value) {
            addCriterion("SolveFile <=", value, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileLike(String value) {
            addCriterion("SolveFile like", value, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileNotLike(String value) {
            addCriterion("SolveFile not like", value, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileIn(List<String> values) {
            addCriterion("SolveFile in", values, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileNotIn(List<String> values) {
            addCriterion("SolveFile not in", values, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileBetween(String value1, String value2) {
            addCriterion("SolveFile between", value1, value2, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveFileNotBetween(String value1, String value2) {
            addCriterion("SolveFile not between", value1, value2, "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionIsNull() {
            addCriterion("SolveDelayDescription is null");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionIsNotNull() {
            addCriterion("SolveDelayDescription is not null");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionEqualTo(String value) {
            addCriterion("SolveDelayDescription =", value, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionNotEqualTo(String value) {
            addCriterion("SolveDelayDescription <>", value, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionGreaterThan(String value) {
            addCriterion("SolveDelayDescription >", value, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("SolveDelayDescription >=", value, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionLessThan(String value) {
            addCriterion("SolveDelayDescription <", value, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionLessThanOrEqualTo(String value) {
            addCriterion("SolveDelayDescription <=", value, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionLike(String value) {
            addCriterion("SolveDelayDescription like", value, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionNotLike(String value) {
            addCriterion("SolveDelayDescription not like", value, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionIn(List<String> values) {
            addCriterion("SolveDelayDescription in", values, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionNotIn(List<String> values) {
            addCriterion("SolveDelayDescription not in", values, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionBetween(String value1, String value2) {
            addCriterion("SolveDelayDescription between", value1, value2, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionNotBetween(String value1, String value2) {
            addCriterion("SolveDelayDescription not between", value1, value2, "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateIsNull() {
            addCriterion("PrecautionDate is null");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateIsNotNull() {
            addCriterion("PrecautionDate is not null");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateEqualTo(Date value) {
            addCriterion("PrecautionDate =", value, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateNotEqualTo(Date value) {
            addCriterion("PrecautionDate <>", value, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateGreaterThan(Date value) {
            addCriterion("PrecautionDate >", value, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateGreaterThanOrEqualTo(Date value) {
            addCriterion("PrecautionDate >=", value, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateLessThan(Date value) {
            addCriterion("PrecautionDate <", value, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateLessThanOrEqualTo(Date value) {
            addCriterion("PrecautionDate <=", value, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateIn(List<Date> values) {
            addCriterion("PrecautionDate in", values, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateNotIn(List<Date> values) {
            addCriterion("PrecautionDate not in", values, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateBetween(Date value1, Date value2) {
            addCriterion("PrecautionDate between", value1, value2, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDateNotBetween(Date value1, Date value2) {
            addCriterion("PrecautionDate not between", value1, value2, "precautionDate");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionIsNull() {
            addCriterion("PrecautionDescription is null");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionIsNotNull() {
            addCriterion("PrecautionDescription is not null");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionEqualTo(String value) {
            addCriterion("PrecautionDescription =", value, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionNotEqualTo(String value) {
            addCriterion("PrecautionDescription <>", value, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionGreaterThan(String value) {
            addCriterion("PrecautionDescription >", value, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("PrecautionDescription >=", value, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionLessThan(String value) {
            addCriterion("PrecautionDescription <", value, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionLessThanOrEqualTo(String value) {
            addCriterion("PrecautionDescription <=", value, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionLike(String value) {
            addCriterion("PrecautionDescription like", value, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionNotLike(String value) {
            addCriterion("PrecautionDescription not like", value, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionIn(List<String> values) {
            addCriterion("PrecautionDescription in", values, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionNotIn(List<String> values) {
            addCriterion("PrecautionDescription not in", values, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionBetween(String value1, String value2) {
            addCriterion("PrecautionDescription between", value1, value2, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionNotBetween(String value1, String value2) {
            addCriterion("PrecautionDescription not between", value1, value2, "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonIsNull() {
            addCriterion("PrecautionReason is null");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonIsNotNull() {
            addCriterion("PrecautionReason is not null");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonEqualTo(String value) {
            addCriterion("PrecautionReason =", value, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonNotEqualTo(String value) {
            addCriterion("PrecautionReason <>", value, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonGreaterThan(String value) {
            addCriterion("PrecautionReason >", value, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonGreaterThanOrEqualTo(String value) {
            addCriterion("PrecautionReason >=", value, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonLessThan(String value) {
            addCriterion("PrecautionReason <", value, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonLessThanOrEqualTo(String value) {
            addCriterion("PrecautionReason <=", value, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonLike(String value) {
            addCriterion("PrecautionReason like", value, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonNotLike(String value) {
            addCriterion("PrecautionReason not like", value, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonIn(List<String> values) {
            addCriterion("PrecautionReason in", values, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonNotIn(List<String> values) {
            addCriterion("PrecautionReason not in", values, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonBetween(String value1, String value2) {
            addCriterion("PrecautionReason between", value1, value2, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonNotBetween(String value1, String value2) {
            addCriterion("PrecautionReason not between", value1, value2, "precautionReason");
            return (Criteria) this;
        }

        public Criteria andBillNoLikeInsensitive(String value) {
            addCriterion("upper(BillNo) like", value.toUpperCase(), "billNo");
            return (Criteria) this;
        }

        public Criteria andLocationNameLikeInsensitive(String value) {
            addCriterion("upper(LocationName) like", value.toUpperCase(), "locationName");
            return (Criteria) this;
        }

        public Criteria andTaskBillCodeLikeInsensitive(String value) {
            addCriterion("upper(TaskBillCode) like", value.toUpperCase(), "taskBillCode");
            return (Criteria) this;
        }

        public Criteria andTaskTypeLikeInsensitive(String value) {
            addCriterion("upper(TaskType) like", value.toUpperCase(), "taskType");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(Remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }

        public Criteria andMakeBillManLikeInsensitive(String value) {
            addCriterion("upper(MakeBillMan) like", value.toUpperCase(), "makeBillMan");
            return (Criteria) this;
        }

        public Criteria andModifierLikeInsensitive(String value) {
            addCriterion("upper(Modifier) like", value.toUpperCase(), "modifier");
            return (Criteria) this;
        }

        public Criteria andInspectDescriptionLikeInsensitive(String value) {
            addCriterion("upper(InspectDescription) like", value.toUpperCase(), "inspectDescription");
            return (Criteria) this;
        }

        public Criteria andInspectPassFLagLikeInsensitive(String value) {
            addCriterion("upper(InspectPassFLag) like", value.toUpperCase(), "inspectPassFLag");
            return (Criteria) this;
        }

        public Criteria andInspectFileLikeInsensitive(String value) {
            addCriterion("upper(InspectFile) like", value.toUpperCase(), "inspectFile");
            return (Criteria) this;
        }

        public Criteria andInspectManLikeInsensitive(String value) {
            addCriterion("upper(InspectMan) like", value.toUpperCase(), "inspectMan");
            return (Criteria) this;
        }

        public Criteria andManagerLikeInsensitive(String value) {
            addCriterion("upper(Manager) like", value.toUpperCase(), "manager");
            return (Criteria) this;
        }

        public Criteria andSolveDescriptionLikeInsensitive(String value) {
            addCriterion("upper(SolveDescription) like", value.toUpperCase(), "solveDescription");
            return (Criteria) this;
        }

        public Criteria andSolveFileLikeInsensitive(String value) {
            addCriterion("upper(SolveFile) like", value.toUpperCase(), "solveFile");
            return (Criteria) this;
        }

        public Criteria andSolveDelayDescriptionLikeInsensitive(String value) {
            addCriterion("upper(SolveDelayDescription) like", value.toUpperCase(), "solveDelayDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionDescriptionLikeInsensitive(String value) {
            addCriterion("upper(PrecautionDescription) like", value.toUpperCase(), "precautionDescription");
            return (Criteria) this;
        }

        public Criteria andPrecautionReasonLikeInsensitive(String value) {
            addCriterion("upper(PrecautionReason) like", value.toUpperCase(), "precautionReason");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ip_taskexecute
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ip_taskexecute
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}